api_platform:
    title: Hello API Platform
    version: 1.0.0
    defaults:
        stateless: true
        cache_headers:
            vary: ['Content-Type', 'Authorization', 'Origin']
        extra_properties:
            standard_put: true
        pagination_items_per_page: 5
        normalization_context:
            skip_null_values: true

    swagger:  
        api_keys:
            apiKey:
                name: Authorization
                type: header
